FROM python:3.9-slim

WORKDIR /app

COPY docker/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ /app/backend/
COPY models/ /app/models/
COPY utils/ /app/utils/

ENV PYTHONPATH=/app
CMD ["python", "backend/app.py"]
